# Generated by Django 4.2.11 on 2024-03-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
    ]
